create database db_bc2311_2;
use db_bc2311_2;

-- DROP TABLE EMPLOYEES;
-- DROP TABLE JOBS;
-- DROP TABLE COUNTRIES;

create table regions(
    REGION_ID INTEGER PRIMARY KEY,
    REGION_NAME VARCHAR(25)
);

create table countries(
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INTEGER,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

create table locations(
    LOCATION_ID INTEGER PRIMARY KEY,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE varchar(12),
    COUNTRY_ID CHAR(2),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

create table departments(
    DEPARTMENT_ID INTEGER PRIMARY KEY,
    DAPARTMENT_NAME VARCHAR(20),
    MANAGER_ID INTEGER,
    LOCATION_ID INTEGER,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

create table jobs (
    JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(35),
    MIN_SALARY DECIMAL(9,2),
    MAX_SALARY DECIMAL(9,2)
);

create table employees (
    EMPLOYEE_ID integer primary key,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(10),
    SALARY DECIMAL(9,2),
    COMMISSION_PCT DECIMAL(9,2),
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER,
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);


create table job_history(
    EMPLOYEE_ID INTEGER,
    START_DATE DATE PRIMARY KEY,
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    DEPARTMENT_ID INTEGER,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);


SELECT * FROM EMPLOYEES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS;
SELECT * FROM JOBS;
SELECT * FROM EMPLOYEES;

INSERT INTO REGIONS VALUES (1, '歐洲');
INSERT INTO REGIONS VALUES (2, '亞洲');
INSERT INTO REGIONS VALUES (3, '美洲');

INSERT INTO COUNTRIES values ('DE', 'Germany', 1);
INSERT INTO COUNTRIES values ('IT', 'Italy', 1);
INSERT INTO COUNTRIES values ('JP', 'Japan', 3);
INSERT INTO COUNTRIES values ('US', 'United States', 2);

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS
, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES (1000, '1297 Via Cola di Rie', '989', 'Roma' , null, 'IT');

INSERT INTO LOCATIONS VALUES (1100, '93091 Calle della Te', '10934', 'Venice' , null, 'IT');
INSERT INTO LOCATIONS VALUES (1200, '2017 Shinjuku-ku', '1689', 'Tokyo' , 'Tokyo JP', null);
INSERT INTO LOCATIONS VALUES (1400, '2014 Jabberwocky Rd', '26192', 'Southlake' , 'Texas', 'US');

    
    